import { keysFactory } from '@/utils/keys';
export const articlesQueryKeys = keysFactory('articles');
export const servicesQueryKeys = keysFactory('services');
export const staffQueryKeys = keysFactory('staff');
export const mediaQueryKeys = keysFactory('media');
export const settingsQueryKeys = keysFactory('settings');
export const adminQueryKeys = keysFactory('admin');
export const equipmentsQueryKeys = keysFactory('equipments');
export const equipmentBrandsQueryKeys = keysFactory('equipment-brands');
export const equipmentCategoriesQueryKeys = keysFactory('equipment-categories');
export const broadcastsQueryKeys = keysFactory('broadcasts');
export const broadcastUnitsQueryKeys = keysFactory('broadcast-units');
